[package]
name = "practical_3"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.42.0", features = ["full"] }
chrono = "0.4.39"
rand = "0.8.5"
libc = "0.2.169"
socket2 = "0.5.8"
tokio-rustls = "0.26.1"
log4rs = "1.3.0"
