[package]
name = "practical_2"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.42.0", features = ["full"] }
chrono = "0.4.39"
libc = "0.2.169"
socket2 = "0.5.8"
rusqlite = { version = "0.33.0", features = ["bundled"] }
